spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=my-sercret-key-from-video

logging.level.org.springframework.jdbc.core=DEBUG
log4j.logger.org.hibernate=DEBUG
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:sqlserver://10.0.1.77;databaseName=db-autocenter;encrypt=true;trustServerCertificate=true;
spring.datasource.username=autohub_adm
spring.datasource.password=PQ9!3%a:K2%r
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# sudo docker build -t autohub-backend .
# sudo docker tag autohub-backend matteusnogueira/autohub-backend:v1.1
# sudo docker push matteusnogueira/autohub-backend:v1.1